package github.hua0512.plugins.command

import java.nio.file.Path

/**
 * Represents the result of a command execution.
 */
data class CommandResult(
  val id: Int = 0,
  /**
   * The command that was executed.
   */
  val command: List<String>,

  /**
   * The exit code of the command.
   */
  val exitCode: Int,

  /**
   * Standard output from the command.
   */
  val stdout: String,

  /**
   * Standard error from the command.
   */
  val stderr: String,

  /**
   * Time taken to execute the command in milliseconds.
   */
  val executionTimeMs: Long,

  /**
   * Files generated by the command.
   */
  val generatedFiles: List<Path> = emptyList(),

  /**
   * Whether the command execution was successful.
   */
  val success: Boolean = exitCode == 0,
)
